#
# Based on https://hub.docker.com/_/sonarqube
#

version: "3.7"

services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    ports:
      - "9000:9000"
    restart: unless-stopped
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=TRUE
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - sonarnet
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    container_name: sonardb
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonar_postgresql:/var/lib/postgresql
      - sonar_postgresql_data:/var/lib/postgresql/data

  sonarscanner:
    container_name: sonarscanner
    image: sonarsource/sonar-scanner-cli
    networks:
      - sonarnet
    volumes:
      - sonarscanner_cache:/opt/sonar-scanner/.sonar/cache
      # change following volume path to your project directory
      - ./:/usr/src

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  sonar_postgresql:
  sonar_postgresql_data:
  sonarscanner_cache:
